### ISSUE TITLE
PBC4cip class

### ISSUE THREAD

**Issue by cshukai** [octavioloyola/PBC4cip#1]
Hello!  Should the default value of distribution evaluator [here](https://github.com/octavioloyola/PBC4cip/blob/3281b645fb52323e7e5939e41ddb9e46eec9bada/PBC4cip/core/PBC4cip.py#L22) be "quinlan gain" rather than "quin lan" ? 

Also, I was wondering if PBC4cip works with balanced data given it is designed for imbalance datasets.  I ran  10 experiments  using 10 different balanced datasets and found accuracy and AUC are exactly the same in each experiment which seems odd . I also ran another 10 experiments using 10 different imbalanced datasets but found difference between accuracy and AUC in each experiment  which looks normal to me. 

Could you also tell me how this program recognize binary labels as  positive and negative class ? Is it by alphabetic order ? If the labels are 'success' and 'failed' , which one is consider positive case  in confusion matrix ?  

Thanks so much !

**Comment by Pirri123** [comment]
Hello!
Thank you for your interest in this project.

You are correct about the default value of the distribution evaluator, I have changed that now.

Yes, PBC4cip works with unbalanced datasets as well, your situation seems a bit odd, but it might depend on the specific datasets you are using.

The labels are determined by alphabetic order yes, so in the case of "success" and "failed" labels, "failed" would come before "success" in the confusion matrix. Also, note that PBC4cip works for multi-class datasets, in that case, the order of the classes in the confusion matrix also is determined alphabetically.
