### ISSUE TITLE
 MultivariateDecisionTree

### ISSUE THREAD

**Issue by cshukai** [octavioloyola/PBC4cip#2]
Hi ,  I ran the following line
`classifier = PBC4cip(distribution_evaluator='hellinger',filtering=True,multivariate=True)`
` patterns = classifier.fit(X_train, y_train)`

but got the following error message

/core/PBC4cip.py", line 105, in fit
    miner.decisionTreeBuilder = MultivariateDecisionTreeBuilder(self.dataset, X, y)

/core/DecisionTreeBuilder.py", line 195, in __init__
    super().__init__(dataset)
TypeError: __init__() missing 2 required positional arguments: 'X' and 'y'

**Comment by Pirri123** [comment]
Multivariate trees are currently a work in progress.
